feat: pass on DH service inquiries to Slack and contact email
The-DataHunt/datahunt-mail-slack pull request #1
Opened 2022-02-23 04:33 UTC by usreon

![iOS 이미지 (1)](https://user-images.githubusercontent.com/79883861/155262134-69065930-5b17-4813-a11c-6460aeaabcfe.jpg)
![iOS 이미지](https://user-images.githubusercontent.com/79883861/155262140-0d96f84e-b2e9-4464-a661-0fae48771453.jpg)

현재 이런 식으로 슬랙 채팅과 메일 들어오고 있습니다.

2022-02-23 04:41 UTC, jjyify requested changes
@usreon 연주님 .env는 푸쉬되면 안됩니다~
.gitignore에 추가해주시고, 배포하는 곳에서 따로 설정해주셔야합니다

2022-02-23 04:42 UTC, jjyify commented on serverless.yml
> +# APP_ID=A033P1LCXAN
@usreon 여기 주석도 제거해주세요.

2022-02-23 04:45 UTC, jjyify requested changes

2022-02-23 04:45 UTC, jjyify commented on src/controllers/contact.controller.ts
> +module.exports.hello = async (event: any) => {
@usreon hello는 예제에 있던건가요? 다른걸로 바꾸면 좋을 것 같아요

2022-02-23 04:45 UTC, jjyify commented on .env
> +PORT='8000'
@usreon .env를 .gitignore에 추가해주세요

2022-02-24 06:39 UTC, usreon commented
새 브랜치로 변경하였습니다.

2022-02-24 06:39 UTC, closed without merging